# Generated by Django 2.2.6 on 2019-11-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=14, verbose_name='energy')),
                ('abs_error', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=14, verbose_name='absolute deviation')),
                ('rel_error', models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=9, verbose_name='relative deviation')),
                ('method', models.CharField(max_length=70, verbose_name='computational method')),
                ('codelink', models.CharField(max_length=140, verbose_name='code repository')),
                ('references', models.TextField(verbose_name='references')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.CharField(choices=[('Hypercube', 'Hypercube'), ('Hexagonal', 'Hexagonal'), ('Triangular', 'Triangular')], max_length=40, verbose_name='type')),
                ('dim', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='dimension')),
                ('pbc', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], verbose_name='periodic boundary conditions')),
            ],
        ),
        migrations.CreateModel(
            name='Energy_TFI',
            fields=[
                ('energy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Energy')),
                ('h', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='h')),
                ('J', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='J')),
            ],
            bases=('core.energy',),
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('H', models.TextField(verbose_name='Hamiltonian')),
                ('n_par', models.IntegerField(verbose_name='number of parameters')),
                ('wikilink', models.CharField(max_length=100, verbose_name='Wikipedia link')),
                ('contributors', models.TextField(verbose_name='contributors')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Graph', verbose_name='graph')),
            ],
        ),
        migrations.AddField(
            model_name='energy',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.System', verbose_name='system'),
        ),
    ]
