# Generated by Django 2.2.7 on 2019-11-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191112_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy_tfi',
            name='energy_ptr',
        ),
        migrations.DeleteModel(
            name='Energy',
        ),
        migrations.DeleteModel(
            name='Energy_TFI',
        ),
    ]
