# Generated by Django 2.2.7 on 2019-11-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191113_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy_TFI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=14)),
                ('h', models.DecimalField(decimal_places=10, max_digits=14)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.System')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
