# Generated by Django 2.2.7 on 2019-11-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_energy_tfi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Energy_TFI',
        ),
    ]
