# Generated by Django 2.2.7 on 2019-11-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_energy_energy_tfi'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='abs_error',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='energy_tfi',
            name='J',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=14),
        ),
    ]
