# Generated by Django 2.2.7 on 2019-11-14 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191113_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy_XXX',
            fields=[
                ('energy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Energy')),
                ('h', models.DecimalField(decimal_places=10, max_digits=14)),
                ('J', models.DecimalField(decimal_places=10, default=0.0, max_digits=14)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.energy',),
        ),
    ]
