# Generated by Django 2.2.7 on 2019-11-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_energy_xxx_j'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energy_xxx',
            old_name='h',
            new_name='J',
        ),
    ]
