# Generated by Django 2.2.7 on 2019-11-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191114_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='rel_error',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
    ]
